body_inertia:
- 0.02456
- 0.0
- 0.0
- 0.0
- 0.05518
- 0.0
- 0.0
- 0.0
- 0.07016
body_mass: 5.6056
hip_positions:
- - 0.1745
  - -0.062
  - 0.0
- - 0.1745
  - 0.062
  - 0.0
- - -0.1745
  - -0.062
  - 0.0
- - -0.1745
  - 0.062
  - 0.0
init_motor_angles:
- 0.0
- -1.178
- 1.658
- 0.0
- -1.178
- 1.658
- 0.0
- -1.178
- 1.658
- 0.0
- -1.178
- 1.658
joint_limits:
  FL_HipX_joint:
    effort: 24.0
    lower: -0.523
    upper: 0.523
    velocity: 26.2
  FL_HipY_joint:
    effort: 24.0
    lower: -2.67
    upper: 0.314
    velocity: 26.2
  FL_Knee_joint:
    effort: 36.0
    lower: 0.524
    upper: 2.792
    velocity: 17.3
  FR_HipX_joint:
    effort: 24.0
    lower: -0.523
    upper: 0.523
    velocity: 26.2
  FR_HipY_joint:
    effort: 24.0
    lower: -2.67
    upper: 0.314
    velocity: 26.2
  FR_Knee_joint:
    effort: 36.0
    lower: 0.524
    upper: 2.792
    velocity: 17.3
  HL_HipX_joint:
    effort: 24.0
    lower: -0.523
    upper: 0.523
    velocity: 26.2
  HL_HipY_joint:
    effort: 24.0
    lower: -2.67
    upper: 0.314
    velocity: 26.2
  HL_Knee_joint:
    effort: 36.0
    lower: 0.524
    upper: 2.792
    velocity: 17.3
  HR_HipX_joint:
    effort: 24.0
    lower: -0.523
    upper: 0.523
    velocity: 26.2
  HR_HipY_joint:
    effort: 24.0
    lower: -2.67
    upper: 0.314
    velocity: 26.2
  HR_Knee_joint:
    effort: 36.0
    lower: 0.524
    upper: 2.792
    velocity: 17.3
leg_joints:
  FL:
  - !!python/tuple
    - FL_HipX_joint
    - axis:
      - -1.0
      - 0.0
      - 0.0
      child: FL_HIP
      limits:
        effort: 24.0
        lower: -0.523
        upper: 0.523
        velocity: 26.2
      origin_rpy:
      - 0
      - 0
      - 0
      origin_xyz:
      - 0.1745
      - 0.062
      - 0.0
      parent: TORSO
      type: revolute
  - !!python/tuple
    - FL_HipY_joint
    - axis:
      - 0.0
      - -1.0
      - 0.0
      child: FL_THIGH
      limits:
        effort: 24.0
        lower: -2.67
        upper: 0.314
        velocity: 26.2
      origin_rpy:
      - 0
      - 0
      - 0
      origin_xyz:
      - 0.0
      - 0.09735
      - 0.0
      parent: FL_HIP
      type: revolute
  - !!python/tuple
    - FL_Knee_joint
    - axis:
      - 0.0
      - -1.0
      - 0.0
      child: FL_SHANK
      limits:
        effort: 36.0
        lower: 0.524
        upper: 2.792
        velocity: 17.3
      origin_rpy:
      - 0
      - 0
      - 0
      origin_xyz:
      - 0.0
      - 0.0
      - -0.2
      parent: FL_THIGH
      type: revolute
  FR:
  - !!python/tuple
    - FR_HipX_joint
    - axis:
      - -1.0
      - 0.0
      - 0.0
      child: FR_HIP
      limits:
        effort: 24.0
        lower: -0.523
        upper: 0.523
        velocity: 26.2
      origin_rpy:
      - 0
      - 0
      - 0
      origin_xyz:
      - 0.1745
      - -0.062
      - 0.0
      parent: TORSO
      type: revolute
  - !!python/tuple
    - FR_HipY_joint
    - axis:
      - 0.0
      - -1.0
      - 0.0
      child: FR_THIGH
      limits:
        effort: 24.0
        lower: -2.67
        upper: 0.314
        velocity: 26.2
      origin_rpy:
      - 0
      - 0
      - 0
      origin_xyz:
      - 0.0
      - -0.09735
      - 0.0
      parent: FR_HIP
      type: revolute
  - !!python/tuple
    - FR_Knee_joint
    - axis:
      - 0.0
      - -1.0
      - 0.0
      child: FR_SHANK
      limits:
        effort: 36.0
        lower: 0.524
        upper: 2.792
        velocity: 17.3
      origin_rpy:
      - 0
      - 0
      - 0
      origin_xyz:
      - 0.0
      - 0.0
      - -0.2
      parent: FR_THIGH
      type: revolute
  RL:
  - !!python/tuple
    - HL_HipX_joint
    - axis:
      - -1.0
      - 0.0
      - 0.0
      child: HL_HIP
      limits:
        effort: 24.0
        lower: -0.523
        upper: 0.523
        velocity: 26.2
      origin_rpy:
      - 0
      - 0
      - 0
      origin_xyz:
      - -0.1745
      - 0.062
      - 0.0
      parent: TORSO
      type: revolute
  - !!python/tuple
    - HL_HipY_joint
    - axis:
      - 0.0
      - -1.0
      - 0.0
      child: HL_THIGH
      limits:
        effort: 24.0
        lower: -2.67
        upper: 0.314
        velocity: 26.2
      origin_rpy:
      - 0
      - 0
      - 0
      origin_xyz:
      - 0.0
      - 0.09735
      - 0.0
      parent: HL_HIP
      type: revolute
  - !!python/tuple
    - HL_Knee_joint
    - axis:
      - 0.0
      - -1.0
      - 0.0
      child: HL_SHANK
      limits:
        effort: 36.0
        lower: 0.524
        upper: 2.792
        velocity: 17.3
      origin_rpy:
      - 0
      - 0
      - 0
      origin_xyz:
      - 0.0
      - 0.0
      - -0.2
      parent: HL_THIGH
      type: revolute
  RR:
  - !!python/tuple
    - HR_HipX_joint
    - axis:
      - -1.0
      - 0.0
      - 0.0
      child: HR_HIP
      limits:
        effort: 24.0
        lower: -0.523
        upper: 0.523
        velocity: 26.2
      origin_rpy:
      - 0
      - 0
      - 0
      origin_xyz:
      - -0.1745
      - -0.062
      - 0.0
      parent: TORSO
      type: revolute
  - !!python/tuple
    - HR_HipY_joint
    - axis:
      - 0.0
      - -1.0
      - 0.0
      child: HR_THIGH
      limits:
        effort: 24.0
        lower: -2.67
        upper: 0.314
        velocity: 26.2
      origin_rpy:
      - 0
      - 0
      - 0
      origin_xyz:
      - 0.0
      - -0.09735
      - 0.0
      parent: HR_HIP
      type: revolute
  - !!python/tuple
    - HR_Knee_joint
    - axis:
      - 0.0
      - -1.0
      - 0.0
      child: HR_SHANK
      limits:
        effort: 36.0
        lower: 0.524
        upper: 2.792
        velocity: 17.3
      origin_rpy:
      - 0
      - 0
      - 0
      origin_xyz:
      - 0.0
      - 0.0
      - -0.2
      parent: HR_THIGH
      type: revolute
motor_names:
- FL_HipX_joint
- FL_HipY_joint
- FL_Knee_joint
- FR_HipX_joint
- FR_HipY_joint
- FR_Knee_joint
- HL_HipX_joint
- HL_HipY_joint
- HL_Knee_joint
- HR_HipX_joint
- HR_HipY_joint
- HR_Knee_joint
num_legs: 4
num_motors: 12
