joint_limits:
  joint1:
    min: -1.57
    max: 1.57
  joint2:
    min: -1.0
    max: 1.0
  joint3:
    min: -0.5
    max: 0.5

mass_properties:
  link1:
    mass: 1.0
    inertia: [0.1, 0.1, 0.1]
  link2:
    mass: 0.5
    inertia: [0.05, 0.05, 0.05]

initial_state:
  position:
    x: 0.0
    y: 0.0
    z: 0.0
  orientation:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0